"use client";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import "react-toastify/dist/ReactToastify.css";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import { Toaster } from "@/components/ui/toaster";
import ReduxProvider from "@/ReduxProvider/ReducProvider";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//TODO complete the error dispatch thing!

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="w-full h-full">
        <ReduxProvider>
          <Navbar />
          {children}
          <Toaster />
          <ProgressBar
            height="2.5px"
            color="#1CABE7"
            options={{ showSpinner: false }}
            shallowRouting
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
