import "./globals.css";
import "remixicon/fonts/remixicon.css";
import { Toaster } from "@/components/ui/toaster";
import ReduxProvider from "@/ReduxProvider/ReducProvider";
import ProgressBar from "@/components/ProgressBar";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="w-full h-full">
        <ReduxProvider>
          <ProgressBar />
          <Navbar />
          {children}
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
