"use client";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import { ToastContainer } from "react-toastify";
import ReduxProvider from "@/ReduxProvider/ReducProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="w-full h-full">
          <ReduxProvider>
            <Navbar />
            {children}
            <ToastContainer />
            <ProgressBar
              height="2.5px"
              color="#1CABE7"
              options={{ showSpinner: false }}
              shallowRouting
            />
          </ReduxProvider>
      </body>
    </html>
  );
}
